name: build
on: push
jobs:
  build:
    if: !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.3
            gemfile: gemfiles/Gemfile-8-0
          - ruby: 3.3
            gemfile: gemfiles/Gemfile-7-2
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      USE_OFFICIAL_GEM_SOURCE: 1
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
